# Generated by Django 5.1.1 on 2024-09-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
