# Generated by Django 5.1.1 on 2024-09-19 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_author_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
